### ISSUE TITLE
To many volumes

### ISSUE THREAD

**Issue by lonix** [icebal/docker-ubooquity#2]
`VOLUME ["/downloads", "/ebooks", "/comics"]`

anything that is not STRICTLY needed should not be added (im guessing /ebooks and /comics) should go. Also i got a feeling you forgot /config (but i dident read the entire thing yet, so i don't know this).

**Comment by icebal** [comment]
Ubooquity doesn't have the a separate config folder, it has to be in the same folder as the main app. i could expose the whole folder, but then i feel it would be better suited for /data than /config at that point.

**Comment by lonix** [comment]
After looking at all files, i have concluded that /app should be /config.
